spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 8 이후에는 MySQLDialect 사용
        dialect.storage_engine: innodb
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      max-lifetime: 50000
      pool-name: HikariCP-Writer

---
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:maindb;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: embedded
      data-locations: classpath:/db/data/data.sql
      schema-locations: classpath:/db/schema/schema.sql

logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
